---
title: "HW4"
author: "Hong Jiang"
date: "October 1, 2015"
output: html_document
---

### #1
#### a) 

```{r}
1:20 #simply a list of number from 1 to 20
```

#### b)
```{r}
20:1 #simply a list of number from 20 to 1,by step one
```
#### c)
```{r}
c(1:20,19:1) #a list of number from 1 to 20, and then from 19 to 1
```
#### d)
```{r}
tmp <- c(4,6,3) # assign tmp with the value (4,6,3)
```
#### e)
```{r}
rep(tmp, times=10) #repeat tem by 10 times
```
#### f)
```{r}
c(rep(tmp,times=10),4) # repeat tem by 10 times and add another 4 since 4 occurs 11 times
```
#### g
```{r}
c(rep(4,times=10),rep(6,times=20),rep(3,times=30)) # repeat 4 by 10 times, repeat 6 by 20 times and repeat 3 by 30 times as required
```

### #2
```{r}
tmp <- seq(3,6,by=0.1)  #create a vector that has the sequence fro 3 to 6 by step 0.1
exp(tmp)*cos(tmp)   # put them into the funtion to get a vector of the values we want
```
### #3
#### a)
```{r}
(0.1^seq(3,36,by=3))*(0.2^seq(1,34,by=3)) #the power to  the 0.1 is a sequence from 3 to 36 by step 3 and the port to the 0.2 is a sequence from 1 to 34 by the step 3
```
#### b)
```{r}
s1 <- 1:25 #create a vector from 1 to 25
(2^s1)/s1 #substitue into the fomula 2^s1/s1
```
### #4
#### a)
```{r}
s1 <- seq(10,100,1) #create a vector sequence from 10 to 100 by step 1
sum(s1^3+4*s1^2) # substitue into the formula and sum all up 
```
#### b)
```{r}
s1 <- seq(1,25,1) #create a vector sequence from 1 to 25 by step 1
sum((2^s1)/s1 + (3^s1)/(s1^2)) #substitue into the formula given and sum them up
```
### #5
#### a)
```{r}
paste("label", 1:30) # use the paste function to paste "label" and concatenate it with a string of number from 1 to 30, with a single space in between
```
#### b)
```{r}
paste("fn", 1:30,sep="") # use the paste function to paste "fn" and concatenate each of them with a string of numbers from 1 to 30;this time, we want there is no space in between so we set sep="" and make it empty
```
### #6
```{r}
set.seed(50)
xVec <- sample(0:999, 250, replace = T)
yVec <- sample(0:999, 250, replace = T) #simply excute the lines as directed
```
#### a)
```{r}
yseq <- yVec[-1] # exclude first number in yVec which is y1, and assign the rest to y1
xseq <- xVec[-length(xVec)] # exclude the last number in xVec which is xn, and assign the rest to x1
yseq-xseq  # sincce yseq strating from y2 to yn, xseq from y1 to yn-2; yseq-xseq will give what we want; like y2-x1, y3-x2,,..,. yn-xn-1
```
#### b)
```{r}
yseq2 <- yVec[-length(yVec)] # assign yseq2 as yVec without the last element yn
xseq2 <- xVec[-1] # assign xseq2 as xVec withou the first elemtn x1
sin(yseq2)/cos(xseq2) # this will give us what we want as yseq2 is from y1 to yn-1 and xseq2 is from x2 to xn
```
#### c)
```{r}
s0 <- seq(1,248,3) #create a sequence from 1 to 248 by 3, namely 1,4,...,248. we createsuch sequence becasue all xs in those positions in that order will be picked out as itself
s1 <- seq(3,250,3) # create a sequence starting from 3 to the end number of xVec which is 250 in this case by step 3, namely 3,6,,..we want such sequence since the xs in those positions will all be deducted later, we want to pick them out first
s2 <- seq(2,249, 3)# create another sequences starting from 2 to 249 in this case by step 3 since the xs in those positions will all be multiplied by 2 and added up
xVec[s0] + 2*xVec[s2] - xVec[s1] # xVeC[so] gives x1,x4,..., xVec[s2] allows us to pick numbers from xVec from the positon 2,5,8,..or simply x2,x5,x8...;xVec[s1] allows us to pick xs from the position 3,6,9..., or simply x3,x6,x9...; therefore, the result will be like x1+2x2-x3,x4+2x5-x6,...,which is we want

#however I found I had misunderstood the problem. It seems lkie we are asked to create the vector(x1+2x2-x3,x2+2x3-x4,...,x248+2x249-x250). so I will redo it in the following: 

xVec[-c(249,250)] + 2*xVec[-c(1,250)]-xVec[-c(1,2)] # we frist exclude the last tow number since those are the only two that will not be itself, then we exclude the frist and last number, since those are the only tow that will not be multiplied by 2; we also exclude first and second elemment as they will not be decucted. therefore, we will have what we want 


```
#### d)
```{r}
 sum(exp(-xVec[-1])/(xVec[-length(xVec)]+10)) # since i is from 1 to n-1, so x(i+1)s is the same as from x2 to xn, so we exclude x1 by xVec[-1]; same reason for xis, they are just the same as from x1 to x(n-1), we we exclude the xn by xVec[-length(xVec)]. after puuting them into the denpendant variable in the formula , we use sum to sum up all terms
```
### #7
#### a)
```{r}
yVec[yVec>600] # we are asked to pick out the values in yVec which are >600, so we put the condition yVec>600, this will be true if the values in yVecs is >600,  then we pick out those values which are in the position true using yVec[]
```
#### b)
```{r}
which(yVec>600) # we are asked to find the index positions of those numbers with values > 600, so we use which funtion, which gives us the index postions
```
#### c)
```{r}
xVec[which(yVec>600)] # we are asked to find the values in xVec that has the same index positions as those values>600 have in yVec, so we find index postions of those ys, and using xVec to pick the values from those index position in xVec
```
#### d)
```{r}
sqrt(abs(xVec-mean(xVec))) #fucntion mean() gives us x bar; abs()gives us the absolute value of the differences between each xs and xbar; take the squre root of those absolute values by sqrt()
```
#### e)
```{r}
length(yVec[yVec>max(yVec)-200]) # first we put condition that if ys in yVec are within 200 of the max values in yVec;it will be true if a number in yVec is bigger than the max-200; yvec[] will pick up all those numbers that stasify the condition; length[] will simply count how many numbers are picked out, which is we want

```
#### f)
```{r}
length(xVec[xVec%%2==0]) # we are asked to find the numbers in xVec that are divisible by 2 and count them, so we put the conditon that if the remainder of xs devided by 2 is 0, using %%2==0; then xVec[] picks out those numbers stasifying the condition; using length[] gives us the total number of values that are stasifed.
```
#### g)
```{r}
xVec[order(yVec)] # we are asked to sort the numbers in xVec in the order of increasing values in yVec. using fucntino order(yVec) will give us the order of increasing values in yVec, then xVec[] generates a new verctor that are the numbers in XVec but placed in the order of order(yVec)
```
#### h)
```{r}
s <- seq(1, 250, 3) # to pick out the elements in yVec at index positions 1,4,7,..  we simply generate a sequence like that, from 1 to 250 by step 3
yVec[s] # yVec[s] pick out those elemnts in the positon as orderd in sequence s
```

### #8
```{r}
1+sum(cumprod(seq(2,38,2)/seq(3,39,2))) # seq(2,38,2) is a list of number like 2,4,6,..,38; seq(3,39,2) is a list of number like 3,5,7,9,..,39. since each term (except ) in the question is generated by multiplying the previous term to the sequence term, we use cumulative product cumprod() which allows us to get the sequence we want; then using sum() sums all the terms up puls the whcih is the first term. 
```








